### ISSUE TITLE
Make host customizeable through an environment variable

### ISSUE THREAD

**Issue by pajlada** [gempir/relaybroker#21]
Right now, the host is `:3333` by default, as set in https://github.com/gempir/relaybroker/blob/master/server.go#L17
Changing that requires you to modify the source code, but it would be preferable if you could change it with an environment variable similar to `BROKERPASS`. Maybe `BROKERHOST`?

**Comment by gempir** [comment]
Thought this was already implemented. Yes this should definitely be implemented.

The Dockerfile should be corrected aswell once this is implemented.
