### ISSUE TITLE
Make us of TLS 

### ISSUE THREAD

**Issue by gempir** [gempir/relaybroker#6]
TLS is the prefered way of connecting to twitch so this would be a great enhancement

**Comment by gempir** [comment]
https://golang.org/pkg/crypto/tls/

**Comment by adamdecaf** [comment]
Is this already done by https://github.com/gempir/relaybroker/commit/031d07728799a9c41ac3403c6faaf51311a6b574 ?

**Comment by gempir** [comment]
Yes sorry. This is an old Ticket.
