### ISSUE TITLE
Open new read connection after X amount of Joins

### ISSUE THREAD

**Issue by gempir** [gempir/relaybroker#7]
opening more read connections will make it possible to join channels faster and have less failure chance because not all data is coming from twitch over one connection.

These connections should probably be also made available to write on or we seperate the read from the write connections.

the connection to the bot/client will still be 1 for sake of convienience, maybe an option for more connections would be nice aswell.

important: the joined channels need to be kept somewhere to not join channels twice and then receive twice the data.

**Comment by pajlada** [comment]
Are you considering allowing multiple read connections for the same
channel? If so, how are you planning on solving the issue of not sending
the same message twice?

**Comment by gempir** [comment]
I didn't plan that but it certainly would be nice. 

Maybe keep multiple connections  and join in all of them but only transfer the data to the client when the first connection causes an error

**Comment by gempir** [comment]
Can't edit on mobile. But a small message cache of sorts could be possible aswell. So it saves a message for like 5 seconds in memory and if a message is already in the cache don't send it again. 

Although the numbers might need tweaking

**Comment by gempir** [comment]
I'm closing this because the original idea is impossible.

Multiple connections don't allow more connections per 10 seconds because that is an IP based ratelimit from tmi.

Multiple read connections would be nice for the future but that belongs in another issue.
