### ISSUE TITLE
Unending messages being added to queue

### ISSUE THREAD

**Issue by pajlada** [gempir/relaybroker#8]
Just connect with wrong password to reproduce.

**Comment by gempir** [comment]
Sending an invalid broker password will close the incoming (innconn) connection already. There should be no log spam.

See here: https://github.com/gempir/relaybroker/blob/master/control.go#L92

**Comment by gempir** [comment]
sending an invalid broker pass will not cause log spam, but sending an invalid oauth key will cause the logs to get spammed with messages of 

> connection is inactive

**Comment by gempir** [comment]
Until this is reproduced agani I'm closing this issue.
